### ISSUE TITLE
Collapse text changeable?

### ISSUE THREAD

**Issue by PsychTechApS** [RyuuKenshi/flutter_collapsible_sidebar#3]
Is it possible to change the "Collapse" text in the expanded sidebar (needed for localization) ?

And is it possible to have an option to specifiy expanded mode as default and/or to programmably change the current mode?

**Comment by RyuuKenshi** [comment]
These things are not possible in the package as is, but you can fork it and make the changes. I think these changes will be very easy to do. I am working on an update to this package but am delayed a bit due to some ongoing personal reasons. I will make these changes by next month and publish it.

If you need the changes fast you can fork it and work on it as mentioned before. Do make a pull request then so that your changes/update is available to everyone.

Best of luck for your project.

**Comment by RyuuKenshi** [comment]
Hi @PsychTechApS ,
In the recent update (v1.0.7) I have added the feature to change toggle button text. Do check it out.

**Comment by RyuuKenshi** [comment]
Do check the updated package with the new features at [https://pub.dev/packages/collapsible_sidebar](url).
